### ISSUE TITLE
задание 1

### ISSUE THREAD

**Issue by 0Sharky** [0Sharky/mitsybishi#1]
Создай 3 папку, в первой папке создай 1 файл в нём напиши все виды рассады для помидоров, во второй папке создай файл со всеми видами рассады для огурцов, в третьей папке создай файл со всеми видами рассады морковки!!!
Срок сдачи до 6.06.6666 или до второго проишествия

**Comment by CMEKAJIo4ka** [comment]
Нехочу

**Comment by 0Sharky** [comment]
ты уволен

**Comment by CMEKAJIo4ka** [comment]
Жалко

**Comment by 0Sharky** [comment]
жалко у пчелки

**Comment by 0Sharky** [comment]
ты принят обратно, работай

**Comment by CMEKAJIo4ka** [comment]
че
уволен

**Comment by 0Sharky** [comment]
только месяц без зп

**Comment by 0Sharky** [comment]
понял?

**Comment by 0Sharky** [comment]
го в метро сникерсы и кирээшке покупать????

**Comment by CMEKAJIo4ka** [comment]
Я лох

**Comment by 0Sharky** [comment]
?

**Comment by 0Sharky** [comment]
уууу

**Comment by 0Sharky** [comment]
ты лооооох тупой!

**Comment by 0Sharky** [comment]
ой не туда написал

- [ ] 

[ ] @ ### **#_пенгЫФВФЫВФЯЧС_**

**Comment by 0Sharky** [comment]
![Uploading scale-17-2.jpg…]()

**Comment by 0Sharky** [comment]
![toyota](https://github.com/0Sharky/mitsybishi/assets/143866193/d60015be-89b7-46df-9126-bc16f960995e)

**Comment by 0Sharky** [comment]
![scale-17-2 2](https://github.com/0Sharky/mitsybishi/assets/143866193/add0552d-0235-469e-9db1-615df466efc5)

**Comment by CMEKAJIo4ka** [comment]
осуждаю

**Comment by 0Sharky** [comment]
https://github.com/whywelive/nke-template.git

**Comment by 0Sharky** [comment]
![Unknown](https://github.com/0Sharky/mitsybishi/assets/143866193/f29471ad-0a60-4d5e-ab27-1d52e714b56a)

**Comment by 0Sharky** [comment]
Привет как дела?

**Comment by 0Sharky** [comment]
<img width="2560" alt="Снимок экрана 2024-04-24 в 13 37 00" src="https://github.com/0Sharky/mitsybishi/assets/143866193/16eb5012-e95d-4f53-bb83-04388af6e3c1">

**Comment by 0Sharky** [comment]
![vaz(](https://github.com/0Sharky/mitsybishi/assets/143866193/b635696a-b11a-4ae4-8644-7e1568908700)
