### ISSUE TITLE
Задание 2 

### ISSUE THREAD

**Issue by 0Sharky** [0Sharky/mitsybishi#3]
Создай ветку  games и создай там 10 текстовых файлов с обзорами на игры от логвинова.
создай и перейди в новую ветку games222 и замени все обозоры логвинова на прикольные анекдоты(1 штука на 1 файл)
объедини 2 ветки. вс> конец задания

**Comment by 0Sharky** [comment]
ало вы живы?

**Comment by CMEKAJIo4ka** [comment]
нифига

**Comment by 0Sharky** [comment]
ура перемена

**Comment by 0Sharky** [comment]
![10](https://github.com/0Sharky/mitsybishi/assets/143866193/f51e8398-480f-46d0-8e4e-88c7abb0f22d)
